### ISSUE TITLE
expose `tokio::net::tcp_listener`?

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-clique/clap-port-flag#12]
In https://github.com/rust-clique/clap-port-flag/pull/11 we're adding an example of how to use this crate with the Hyper HTTP server. To get it to work, some glue is required:

```rust
  let args = Cli::from_args();
  let listener = args.port.bind()?;
  let handle = tokio::reactor::Handle::current();
  let listener = tokio::net::TcpListener::from_std(listener, &handle)?;
```

This seems like boilerplate that would probably be copy-pasted from between projects, which makes it seem like a prime candidate to create a method for.

I was thinking something like this:
```rust
  let args = Cli::from_args();
  let listener = args.port.bind_tokio()?;
```

The name here could probably use some work (cc/ @killercup, suggestions?) but I reckon the result would be really useful. 

Setting up a complete HTTP server would then only require the following:
```rust

#[derive(Debug, StructOpt)]
struct Cli {
  #[structopt(flatten)]
  port: Port,
}

fn main() -> Result<(), Box<std::error::Error>> {
  let args = Cli::from_args();
  let listener = args.port.bind_tokio()?;

  let server = Server::builder(listener.incoming())
    .serve(|| service_fn_ok(|_| Response::new(Body::from("Hello World"))))
    .map_err(|e| eprintln!("server error: {}", e));

  tokio::run(server);
  Ok(())
}
```
Which I think is starting to become short enough that people can memorize it!

## Drawbacks
This would add `tokio` as a dependency which adds a bit of overhead during compilation. But given that all major frameworks depend on it, it's probably safe to say it won't introduce any new dependencies for production systems.

**Comment by killercup** [comment]
Hm. Not sure I agree with this. I can see how this might come in handy, but I have two questions:

- How many crates will use hyper directly and would you also want to support other libraries?
- How many people would expect a crate called clap-port-flag to have tokio-specific code? (Similar to my comment in <https://github.com/rust-clique/clap-verbosity-flag/issues/5>, I wouldn't)

I think my main issue with this is that it is very specific to Hyper. If it where easier in hyper to use an existing socket, we wouldn't need this. In actix-web, e.g., you can pretty much to `server.listen(args.port.bind()?)` IIRC

**Comment by yoshuawuyts** [comment]
> If it where easier in hyper to use an existing socket, we wouldn't need this.

Yeah I actually agree with this. Good point.

**Comment by yoshuawuyts** [comment]
`Server::from_tcp()` just landed in Hyper! https://github.com/hyperium/hyper/pull/1624
